### ISSUE TITLE
Company.NRR30 & Company.NRRTotal are wrongly typed

### ISSUE THREAD

**Issue by nic-gibson** [darrenparkinson/planhat#2]
Both these fields are typed as "number" by Planhat and often contain floats (at least in our case). The struct defines them as int causing errors. 

I'd give you a pull request but I don't have access to the accessor generator you're using.

**Comment by darrenparkinson** [comment]
Hi. I think you can just run `go generate` to create the accessors?

**Comment by nic-gibson** [comment]
I'll take a look (sorry for the slow reply - holiday)

**Comment by darrenparkinson** [comment]
No problem. All good. Look forward to further updates. Give me a nudge if you have any trouble.

**Comment by nic-gibson** [comment]
@darrenparkinson - I've finally had the time to build a pull request for this. #3
